#!/bin/zsh

# Zig aliases for CC and CXX
function z++(){
if (($+commands[zig]));then
     zig c++ -std=c++2b -fexperimental-library $argv
else
    echo 'install zig language compiler on your system'
fi

}

z++ $*
